project:
  type: website
  output-dir: docs

website:
  title: ineelhere
  navbar:
    logo: https://yt3.googleusercontent.com/COcDOdM34eRf7LXZns3q09aIURGSxeE4FI0W2qTqXD9eoyjUVExPmosmnSlcrEknimPlbNj4CNo=s160-c-k-c0x00ffffff-no-rj
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu:
          - text: ClintrialX
            href: https://cran.r-project.org/package=clintrialx
          - text: 30 Days of Pharmaverse
            href: https://ineelhere.github.io/30-days-of-pharmaverse
          - text: 30 Days of AI - Streamlit
            href: https://github.com/ineelhere/30DaysOfAI-Streamlit
          - text: shiny.emojirain
            href: https://github.com/ineelhere/shiny.emojirain
          - text: shiny.ollama
            href: https://github.com/ineelhere/shiny.ollama/
          - text: Building Systems with ChatGPT API
            href: https://ineelhere.github.io/Building-Systems-with-the-ChatGPT-API/
          - text: Code With Go
            href: https://ineelhere.gitbook.io/code-with-go/
          - text: Curated
            href: https://curated.streamlit.app/
          - text: India Fights COVID19
            href: https://indiafightscovid19.streamlit.app/
    right:
      - icon: github
        href: https://github.com/ineelhere
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/ineehere
        aria-label: Twitter
  page-footer:
    left: Â© 2026 Indraneel Chakraborty. All rights reserved.
    right:
      - icon: github
        href: https://github.com/ineelhere/
      - icon: twitter
        href: https://x.com/ineelhere

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    highlight-style: github
